"""
SQLAlchemy ORM Model: AlertORM
================================
Notification records generated by the AI pipeline.

Design Notes:
    - ``ai_recommendation`` is stored as TEXT (can be very long LLM output).
    - The table has a compound index on (parcel_id, is_read) to make the
      common "fetch unread alerts" query fast.
    - A partial index on ``is_read = false`` further optimises the badge
      count query that runs on every app open.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum as SAEnum,
    Float,
    ForeignKey,
    Index,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.db.base import Base
from app.domain.entities.alert import Alert, AlertSeverity, AlertType

if TYPE_CHECKING:
    from app.infrastructure.db.models.parcel_orm import ParcelORM


class AlertORM(Base):
    """ORM representation of the ``alerts`` table."""

    __tablename__ = "alerts"

    __table_args__ = (
        Index("ix_alerts_parcel_read", "parcel_id", "is_read"),
        Index("ix_alerts_parcel_id", "parcel_id"),
        # Partial index optimises the unread badge count query
        Index(
            "ix_alerts_unread_partial",
            "parcel_id",
            postgresql_where="is_read = false",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    parcel_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("parcels.id", ondelete="CASCADE"),
        nullable=False,
        comment="Affected parcel. Cascaded on parcel deletion.",
    )
    alert_type: Mapped[AlertType] = mapped_column(
        SAEnum(AlertType, name="alerttype", create_constraint=True, validate_strings=True),
        nullable=False,
        comment="ANOMALY (satellite) or WEATHER (forecast).",
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        SAEnum(AlertSeverity, name="alertseverity", create_constraint=True, validate_strings=True),
        nullable=False,
        default=AlertSeverity.MEDIUM,
        server_default=AlertSeverity.MEDIUM.value,
        comment="Urgency classification.",
    )
    title: Mapped[str] = mapped_column(
        String(255), nullable=False, comment="Short alert headline."
    )
    description: Mapped[str] = mapped_column(
        Text, nullable=False, comment="Detailed description of the condition detected."
    )
    ai_recommendation: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="RAG-generated action plan (may be long-form LLM output).",
    )
    is_read: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        index=True,
        comment="Whether the farmer has acknowledged this alert.",
    )
    read_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp when the farmer read the alert.",
    )
    triggered_value: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True, comment="Value that crossed the alert threshold."
    )
    threshold_value: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True, comment="The threshold that was breached."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    parcel: Mapped["ParcelORM"] = relationship(
        "ParcelORM",
        back_populates="alerts",
        lazy="noload",
    )

    # ------------------------------------------------------------------
    # Mapping
    # ------------------------------------------------------------------

    def to_domain(self) -> Alert:
        return Alert(
            id=self.id,
            parcel_id=self.parcel_id,
            alert_type=AlertType(self.alert_type),
            severity=AlertSeverity(self.severity),
            title=self.title,
            description=self.description,
            ai_recommendation=self.ai_recommendation,
            is_read=self.is_read,
            read_at=self.read_at,
            triggered_value=self.triggered_value,
            threshold_value=self.threshold_value,
            created_at=self.created_at,
        )

    @classmethod
    def from_domain(cls, alert: Alert) -> "AlertORM":
        return cls(
            id=alert.id,
            parcel_id=alert.parcel_id,
            alert_type=alert.alert_type,
            severity=alert.severity,
            title=alert.title,
            description=alert.description,
            ai_recommendation=alert.ai_recommendation,
            is_read=alert.is_read,
            read_at=alert.read_at,
            triggered_value=alert.triggered_value,
            threshold_value=alert.threshold_value,
            created_at=alert.created_at,
        )

    def __repr__(self) -> str:
        return (
            f"<AlertORM id={self.id!s} parcel={self.parcel_id!s} "
            f"type={self.alert_type!r} severity={self.severity!r} read={self.is_read}>"
        )
