"""init_database

Revision ID: cc0c9a545dc5
Revises: 
Create Date: 2026-03-25 22:17:26.886549+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'cc0c9a545dc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Unique lowercase email address.'),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False, comment='Argon2/Bcrypt hashed password. Never store plain text.'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's display name."),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False, comment='False = suspended account that cannot authenticate.'),
    sa.Column('is_superuser', sa.Boolean(), server_default='False', nullable=False, comment='True = admin privileges.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # Functional index on lower(email). Use raw SQL via op.execute — passing
    # sa.text("lower(email)") to create_index renders the column as a quoted
    # string literal lower('email'), producing a constant key that collides
    # on every second row. Raw DDL guarantees the column is referenced.
    op.execute(
        "CREATE UNIQUE INDEX uix_users_email_lower ON users (lower(email))"
    )
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False, comment='Globally unique identifier for the parcel.'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='FK → users.id. Cascaded on user deletion.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable label for the parcel.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional free-text notes from the farmer.'),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='PostGIS MULTIPOLYGON geometry (WGS84, SRID 4326).'),
    sa.Column('area_ha', sa.Float(), nullable=False, comment='Pre-computed area in hectares.'),
    sa.Column('srid', sa.Integer(), server_default='4326', nullable=False, comment='Spatial Reference Identifier (4326 = WGS84).'),
    sa.Column('crop_type', sa.Enum('WHEAT', 'CORN', 'SUNFLOWER', 'SOYBEAN', 'RAPESEED', 'BARLEY', 'POTATO', 'SUGAR_BEET', 'VINEYARD', 'ORCHARD', 'OTHER', 'UNKNOWN', name='croptype', create_constraint=True), server_default='UNKNOWN', nullable=False, comment='Current crop planted on this parcel.'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ARCHIVED', name='parcelstatus', create_constraint=True), server_default='PENDING', nullable=False, comment='Lifecycle status of the parcel.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of record creation.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification.'),
    sa.Column('last_ndvi', sa.Float(), nullable=True, comment='Most recent NDVI value from satellite imagery (-1.0 to 1.0).'),
    sa.Column('last_ndvi_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when last_ndvi was measured.'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parcels_geometry', 'parcels', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_parcels_owner_id', 'parcels', ['owner_id'], unique=False)
    op.create_index('ix_parcels_owner_status', 'parcels', ['owner_id', 'status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False, comment='Affected parcel. Cascaded on parcel deletion.'),
    sa.Column('alert_type', sa.Enum('ANOMALY', 'WEATHER', name='alerttype', create_constraint=True), nullable=False, comment='ANOMALY (satellite) or WEATHER (forecast).'),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity', create_constraint=True), server_default='MEDIUM', nullable=False, comment='Urgency classification.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short alert headline.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the condition detected.'),
    sa.Column('ai_recommendation', sa.Text(), nullable=True, comment='RAG-generated action plan (may be long-form LLM output).'),
    sa.Column('is_read', sa.Boolean(), server_default='False', nullable=False, comment='Whether the farmer has acknowledged this alert.'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when the farmer read the alert.'),
    sa.Column('triggered_value', sa.Float(), nullable=True, comment='Value that crossed the alert threshold.'),
    sa.Column('threshold_value', sa.Float(), nullable=True, comment='The threshold that was breached.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index('ix_alerts_parcel_id', 'alerts', ['parcel_id'], unique=False)
    op.create_index('ix_alerts_parcel_read', 'alerts', ['parcel_id', 'is_read'], unique=False)
    op.create_index('ix_alerts_unread_partial', 'alerts', ['parcel_id'], unique=False, postgresql_where='is_read = false')
    op.create_table('ndvi_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False, comment='Links to the parent parcel. Cascaded on parcel deletion.'),
    sa.Column('date_captured', sa.Date(), nullable=False, comment='Calendar date of the satellite pass (UTC).'),
    sa.Column('mean_ndvi', sa.Float(), nullable=False, comment='Mean NDVI over the parcel area. Range: [-1.0, 1.0].'),
    sa.Column('cloud_coverage', sa.Float(), server_default='0.0', nullable=False, comment='Percentage of parcel obscured by cloud cover [0–100].'),
    sa.Column('pixel_count', sa.Integer(), nullable=True, comment='Number of satellite pixels averaged.'),
    sa.Column('is_interpolated', sa.Boolean(), server_default='False', nullable=False, comment='True if this NDVI was gap-filled (high cloud coverage).'),
    sa.Column('source', sa.String(length=64), server_default='UNKNOWN', nullable=False, comment='Satellite source identifier (e.g. sentinel-2, landsat-8).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_id', 'date_captured', 'source', name='uq_ndvi_parcel_date_source')
    )
    op.create_index('ix_ndvi_parcel_date', 'ndvi_records', ['parcel_id', 'date_captured'], unique=False)
    op.create_index('ix_ndvi_parcel_id', 'ndvi_records', ['parcel_id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False, comment='Parent parcel. Cascaded on deletion.'),
    sa.Column('forecast_date', sa.Date(), nullable=False, comment='The calendar date this forecast applies to.'),
    sa.Column('temp_max_c', sa.Float(), nullable=False, comment='Maximum air temperature (°C).'),
    sa.Column('temp_min_c', sa.Float(), nullable=False, comment='Minimum air temperature (°C).'),
    sa.Column('humidity_pct', sa.Float(), nullable=False, comment='Relative humidity percentage [0–100].'),
    sa.Column('precipitation_mm', sa.Float(), server_default='0.0', nullable=False, comment='Expected precipitation in millimetres.'),
    sa.Column('wind_speed_kmh', sa.Float(), server_default='0.0', nullable=False, comment='Mean wind speed (km/h).'),
    sa.Column('uv_index', sa.Float(), nullable=True, comment='UV index (0–11+).'),
    sa.Column('weather_code', sa.Integer(), nullable=True, comment='WMO weather interpretation code.'),
    sa.Column('source', sa.String(length=64), server_default='open-meteo', nullable=False, comment='API/provider name (e.g. open-meteo, openweathermap).'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this forecast was fetched from the API.'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_id', 'forecast_date', 'source', name='uq_weather_parcel_date_source')
    )
    op.create_index('ix_weather_parcel_date', 'weather_forecasts', ['parcel_id', 'forecast_date'], unique=False)
    op.create_index('ix_weather_parcel_id', 'weather_forecasts', ['parcel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_parcel_id', table_name='weather_forecasts')
    op.drop_index('ix_weather_parcel_date', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index('ix_ndvi_parcel_id', table_name='ndvi_records')
    op.drop_index('ix_ndvi_parcel_date', table_name='ndvi_records')
    op.drop_table('ndvi_records')
    op.drop_index('ix_alerts_unread_partial', table_name='alerts', postgresql_where='is_read = false')
    op.drop_index('ix_alerts_parcel_read', table_name='alerts')
    op.drop_index('ix_alerts_parcel_id', table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_parcels_owner_status', table_name='parcels')
    op.drop_index('ix_parcels_owner_id', table_name='parcels')
    op.drop_index('ix_parcels_geometry', table_name='parcels', postgresql_using='gist')
    op.drop_table('parcels')
    op.drop_index('uix_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
